
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author brent
 */


public class ATM extends javax.swing.JFrame {
private double balance = 0.0;
    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        DepositButton = new javax.swing.JButton();
        AccountButton = new javax.swing.JButton();
        TransferButton = new javax.swing.JButton();
        WithdrawButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ACCOUNT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ACCOUNT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ATM MANAGEMENT SYSTEM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel5.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 100, 30));

        DepositButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DepositButton.setText("Deposit");
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });
        jPanel5.add(DepositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 140, 53));

        AccountButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AccountButton.setText("Account");
        AccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountButtonActionPerformed(evt);
            }
        });
        jPanel5.add(AccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 50));

        TransferButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TransferButton.setText("Transfer");
        TransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferButtonActionPerformed(evt);
            }
        });
        jPanel5.add(TransferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 50));

        WithdrawButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WithdrawButton.setText("Withdraw");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });
        jPanel5.add(WithdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 140, 53));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 650, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountButtonActionPerformed
            JOptionPane.showMessageDialog(null,"Current Balance:" + "$"+ balance );
    

    }//GEN-LAST:event_AccountButtonActionPerformed

    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed
      String amount = JOptionPane.showInputDialog(null, "Enter amount to withdraw:");
    if(amount != null && !amount.isEmpty()) {
        double withdrawAmount = Double.parseDouble(amount);
        if(withdrawAmount <= balance) {
            balance -= withdrawAmount;
            JOptionPane.showMessageDialog(null, "Withdrawal successful. New Balance: " + "$"+ balance);
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient funds!");
        }
    }                                              
      
    }//GEN-LAST:event_WithdrawButtonActionPerformed

    private void TransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferButtonActionPerformed
 String amount = JOptionPane.showInputDialog(null, "Enter amount to transfer:");
    if(amount != null && !amount.isEmpty()) {
        double transferAmount = Double.parseDouble(amount);
        if(transferAmount <= balance) {
            String accountNumber = JOptionPane.showInputDialog(null, "Enter account number to transfer:");
            if(accountNumber != null && !accountNumber.isEmpty()) {
                // Assuming you have a method to transfer funds to another account
                boolean transferSuccess = transferToAnotherAccount(accountNumber, transferAmount);
                if(transferSuccess) {
                    balance -= transferAmount;
                    JOptionPane.showMessageDialog(null, "Transfer successful. New Balance: " + "$"+ balance);
                } else {
                    JOptionPane.showMessageDialog(null, "Transfer failed. Invalid account number.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Transfer cancelled.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient funds!");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Invalid amount entered.");
    }
    

    }//GEN-LAST:event_TransferButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Lorenzo Brent Reed C. Varca, ITE - 232");
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositButtonActionPerformed
      String amount = JOptionPane.showInputDialog(null, "Enter amount to deposit:");
    if(amount != null && !amount.isEmpty()) {
        double depositAmount = Double.parseDouble(amount);
        balance += depositAmount;
        JOptionPane.showMessageDialog(null, "Deposit successful. New Balance: " + "$" + balance);
    }
    }//GEN-LAST:event_DepositButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountButton;
    private javax.swing.JButton DepositButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton TransferButton;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private boolean transferToAnotherAccount(String accountNumber, double transferAmount) {
return true;
    }

   

    
}
